### ISSUE TITLE
Quest Bug RXP Survivel Guide

### ISSUE THREAD

**Issue by ngwarrior** [jazminite/RXPGuides_Quests#12]
On the Alliance side i found a bug while questing the RXP Survivel Guide 1-20.
From the Darkshore/Ashenval step 71 Turn in Orendil's Cure: 
I accidantly allready did the Quest and it got stuck. 
I don't know how to fix this issue, could you help?

Best Regards
Nxwarrior

**Comment by jazminite** [comment]
This repo is for a custom guide.
It sounds like you are having an issue with the main RXP addon guide.
You can join their discord to get assistance: [discord.gg/restedxp](https://discord.gg/restedxp)
